#!perl
BEGIN { 
    $ENV{CATALYST_ENGINE} ||= 'HTTP';
    $ENV{CATALYST_SCRIPT_GEN} = 40;
}  

use strict;
use FindBin;
use lib 'lib';
use Devel::ebug;
use Devel::ebug::HTTP;

my $filename = shift;
die "Usage: ebug_http filename\n" unless $filename;

my $ebug = Devel::ebug->new();
$ebug->program($filename);
$ebug->load;
$Devel::ebug::HTTP::ebug = $ebug;

use Catalyst::ScriptRunner;
Catalyst::ScriptRunner->run('Devel::ebug::HTTP', 'Server');

1;

__END__

=head1 NAME

ebug_http - A simple, extensible web Perl debugger

=head1 SYNOPSIS

  % ebug_http calc.pl

=head1 DESCRIPTION

ebug is a web-based front end to L<Devel::ebug>. It is a simple Perl
debugger. When run, it will report back how to contact its front page.

=head1 SEE ALSO

L<Devel::ebug>

=head1 AUTHOR

Leon Brocard, C<< <acme@astray.com> >>

=head1 COPYRIGHT

Copyright (C) 2005, Leon Brocard

This program is free software; you can redistribute it or modify it
under the same terms as Perl itself.
